
drafter: |
  # Rédaction de la sous-partie {section_title}
  ## Contexte et objectifs
  {section_plan}
  ## Consignes de rédaction
  - Utilise un maximum d'analyses et citations du corpus fourni.
  - Intègre chaque citation entre guillemets et au format APA : (Auteur, Année).
  - Structure en markdown.
  - Termine par un résumé flash de 200-500 tokens.
  ## Statistiques du corpus
  - Nombre d'éléments: {corpus_count}
  - Score moyen: {avg_score}
  - Mots-clés détectés: {keywords_found}
  ## Corpus à utiliser
  {corpus}
  ## Résumés flash précédents
  {previous_summaries}

refiner: |
  Tu es un éditeur de style. Réécris et condense le texte fourni en assurant cohérence,
  clarté et fluidité, en gardant les citations APA. Harmonise le ton et la terminologie.
